# Generated by Django 3.1.5 on 2022-07-26 12:15

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeqaleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=50)),
                ('yazi', models.TextField()),
                ('sekil', models.ImageField(upload_to='meqale_sekilleri')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='basliq')),
                ('yaranma_tarixi', models.DateTimeField(auto_now_add=True)),
                ('redakte_tarixi', models.DateTimeField(auto_now=True)),
                ('kateqoriya', models.ManyToManyField(related_name='meqale', to='blog.KateqoriyaModel')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meqaleler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Məqalə',
                'verbose_name_plural': 'Məqalələr',
                'db_table': 'meqale',
            },
        ),
    ]
