# Generated by Django 3.1.5 on 2022-07-26 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20220726_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerhModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi', models.TextField()),
                ('yaranma_tarixi', models.DateTimeField(auto_now_add=True)),
                ('redakte_tarixi', models.DateTimeField(auto_now=True)),
                ('meqale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serhler', to='blog.meqalemodel')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serhler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Şərhlər',
                'db_table': 'serh',
            },
        ),
    ]
