# Generated by Django 3.1.5 on 2022-08-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_serhmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serhmodel',
            options={'verbose_name': 'Şərh', 'verbose_name_plural': 'Şərhlər'},
        ),
    ]
