from .elaqe import ElaqeFormView
from .anasehife import AnaSehife
from .kateqoriya import KategoriyaList
from .meqalelerim import meqalelerim
from .detay import Detay
from .meqale_yaz import MeqaleYazCreateView
from .meqale_redakte import MeqaleRedakteUpdateView
from .meqale_sil import MeqaleSilDeleteView
from .serh_sil import serh_sil
