from .elaqe import elaqe
from .anasehife import AnaSehife
from .kateqoriya import kateqoriya
from .meqalelerim import meqalelerim
from .detay import Detay
from .meqale_yaz import meqale_yaz
from .meqale_redakte import meqale_redakte
from .meqale_sil import meqale_sil
from .serh_sil import serh_sil
